# Generated by Django 4.2.9 on 2024-01-30 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'سنسور',
                'verbose_name_plural': 'سنسورها',
            },
        ),
        migrations.CreateModel(
            name='LightIntensitySensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sense.sensor')),
            ],
            options={
                'verbose_name': 'سنسور\u200cهای شدت نور',
            },
            bases=('sense.sensor',),
        ),
        migrations.CreateModel(
            name='SoilMoistureSensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sense.sensor')),
                ('analog_pin', models.IntegerField(verbose_name='شماره پین آنالوگ')),
                ('digital_pin', models.IntegerField(verbose_name='شماره پین دیجیتال')),
            ],
            options={
                'verbose_name': 'سنسور رطوبت خاک',
                'verbose_name_plural': 'سنسورهای رطوبت خاک',
            },
            bases=('sense.sensor',),
        ),
        migrations.CreateModel(
            name='TemperatureHumiditySensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sense.sensor')),
                ('tp', models.CharField(choices=[('DHT22', 'DHT22')], max_length=128, verbose_name='نوع سنسور')),
                ('am2302_pin', models.IntegerField(verbose_name='پین am2302')),
            ],
            options={
                'verbose_name': 'سنسور دما و رطوبت',
                'verbose_name_plural': 'سنسورهای دما و رطوبت',
            },
            bases=('sense.sensor',),
        ),
        migrations.CreateModel(
            name='UltrasonicSensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sense.sensor')),
                ('trig_pin', models.IntegerField(verbose_name='پین trig')),
                ('echo_pin', models.IntegerField(verbose_name='پین echo')),
                ('total_height_cm', models.IntegerField(help_text='به سانتی\u200cمتر وارد کنید.', verbose_name='ارتفاع مخزن')),
            ],
            options={
                'verbose_name': 'سنسور اولتراسونیک',
                'verbose_name_plural': 'سنسور\u200cهای اولتراسونیک',
            },
            bases=('sense.sensor',),
        ),
    ]
