# Generated by Django 4.2.9 on 2024-01-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lightintensitysensor',
            options={'verbose_name': 'سنسورهای شدت\u200cنور'},
        ),
    ]
