# Generated by Django 4.2.9 on 2024-01-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sense', '0002_alter_lightintensitysensor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lightintensitysensor',
            options={'verbose_name': 'سنسور شدت\u200cنور', 'verbose_name_plural': 'سنسورهای شدت\u200cنور'},
        ),
    ]
