# Generated by Django 4.2.9 on 2024-01-30 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('result', models.JSONField(verbose_name='نتیجه سنسور')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='sense.sensor', verbose_name='سنسور مربوطه')),
            ],
            options={
                'verbose_name': 'نتیجه سنسور',
                'verbose_name_plural': 'نتایج سنسورها',
            },
        ),
        migrations.CreateModel(
            name='SensorMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_monitor', models.DateTimeField(blank=True, null=True, verbose_name='آخرین پایش')),
                ('time_between_sense', models.DurationField(verbose_name='مدت زمان تا پایش سنسور')),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='monitors', to='sense.sensor', verbose_name='سنسور مربوطه')),
            ],
            options={
                'verbose_name': 'پایشگر سنسور',
                'verbose_name_plural': 'پایشگران سنسورها',
            },
        ),
    ]
