# Generated by Django 4.2.9 on 2024-01-31 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sense', '0004_sensorfigure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buzzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField(verbose_name='شماره پین')),
            ],
            options={
                'verbose_name': 'هشداردهنده',
                'verbose_name_plural': 'هشداردهندگان',
            },
        ),
        migrations.CreateModel(
            name='SensorBuzz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.BooleanField(default=True, verbose_name='روشن است؟')),
                ('pitch', models.IntegerField(verbose_name='اوج صدا')),
                ('duration', models.IntegerField(verbose_name='طول صدا')),
                ('for_how_long', models.DurationField(verbose_name='مدت زمان انتظار')),
                ('sensor_result_filters', models.JSONField(verbose_name='فیلترهای روز نتیجه سنسور')),
                ('last_effort', models.DateTimeField(blank=True, null=True)),
                ('buzzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzzes', to='control.buzzer', verbose_name='هشداردهنده\u200cی مربوطه')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzzes', to='sense.sensor', verbose_name='سنسور مربوطه')),
            ],
            options={
                'verbose_name': 'هشداردهنده',
                'verbose_name_plural': 'هشداردهندگان',
            },
        ),
    ]
