# Generated by Django 4.2.9 on 2024-01-31 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorbuzz',
            options={'verbose_name': 'هشدار سنسور', 'verbose_name_plural': 'هشدارهای سنسور'},
        ),
    ]
